import {
  Code2,
  Container,
  Database,
  Layers3,
  ServerCog,
  Terminal,
  Workflow,
} from "lucide-react"

export const courses = [
  {
    id: "frontend",
    number: "01",
    category: "FRONTEND",
    title: "Frontend Engineering",
    description:
      "Từ giao diện đầu tiên đến trải nghiệm web chỉn chu, nhanh và dễ dùng.",
    price: 899,
    icon: Layers3,
    accent: "text-primary bg-primary/10",
    glow: "bg-primary/10",
    topics: [
      "HTML, CSS và JavaScript",
      "React, Next.js và TypeScript",
      "Tư duy xây dựng component",
    ],
    stack: ["React", "Next.js", "TypeScript"],
  },
  {
    id: "backend",
    number: "02",
    category: "BACKEND",
    title: "Backend & System Design",
    description:
      "Thiết kế API, xử lý dữ liệu và hiểu cách một hệ thống vận hành.",
    price: 1099,
    icon: Terminal,
    accent: "text-sdev-cyan bg-sdev-cyan/10",
    glow: "bg-sdev-cyan/10",
    topics: [
      "Thiết kế API",
      "Node.js và PostgreSQL",
      "Kiến trúc và triển khai",
    ],
    stack: ["Node.js", "PostgreSQL", "Docker"],
  },
  {
    id: "fullstack",
    number: "03",
    category: "FULLSTACK",
    title: "The Fullstack Path",
    description:
      "Kết nối giao diện, API và dữ liệu để xây dựng một sản phẩm web hoàn chỉnh.",
    price: 1799,
    icon: Code2,
    accent: "text-sdev-pink bg-sdev-pink/10",
    glow: "bg-sdev-pink/10",
    topics: [
      "Giao diện và luồng người dùng",
      "API, dữ liệu và xác thực",
      "Hoàn thiện ứng dụng end-to-end",
    ],
    stack: ["Next.js", "Prisma", "Cloud"],
  },
  {
    id: "nextjs-co-ban",
    number: "04",
    category: "FRONTEND",
    title: "Next.js Cơ bản",
    description: "Nắm nền tảng Next.js để xây trang web có cấu trúc rõ ràng.",
    price: 499,
    icon: Layers3,
    accent: "text-primary bg-primary/10",
    glow: "bg-primary/10",
    topics: [
      "App Router và route",
      "Server và Client Components",
      "Lấy dữ liệu và điều hướng",
    ],
    stack: ["Next.js", "React", "TypeScript"],
  },
  {
    id: "nextjs-nang-cao",
    number: "05",
    category: "FRONTEND",
    title: "Next.js Nâng cao",
    description: "Đi sâu vào hiệu năng, dữ liệu và kiến trúc ứng dụng Next.js.",
    price: 799,
    icon: Code2,
    accent: "text-primary bg-primary/10",
    glow: "bg-primary/10",
    topics: [
      "Rendering và caching",
      "Tối ưu hiệu năng",
      "Kiến trúc ứng dụng lớn",
    ],
    stack: ["Next.js", "Caching", "Performance"],
  },
  {
    id: "nestjs-co-ban",
    number: "06",
    category: "BACKEND",
    title: "NestJS Cơ bản",
    description: "Bắt đầu xây API có tổ chức với NestJS và TypeScript.",
    price: 549,
    icon: ServerCog,
    accent: "text-sdev-cyan bg-sdev-cyan/10",
    glow: "bg-sdev-cyan/10",
    topics: [
      "Module, controller và service",
      "Validation và xử lý lỗi",
      "Kết nối cơ sở dữ liệu",
    ],
    stack: ["NestJS", "TypeScript", "REST API"],
  },
  {
    id: "nestjs-nang-cao",
    number: "07",
    category: "BACKEND",
    title: "NestJS Nâng cao",
    description: "Thiết kế backend vững vàng cho các luồng nghiệp vụ phức tạp.",
    price: 849,
    icon: ServerCog,
    accent: "text-sdev-cyan bg-sdev-cyan/10",
    glow: "bg-sdev-cyan/10",
    topics: [
      "Xác thực và phân quyền",
      "Kiểm thử ứng dụng",
      "Tối ưu kiến trúc API",
    ],
    stack: ["NestJS", "Auth", "Testing"],
  },
  {
    id: "postgresql",
    number: "08",
    category: "DỮ LIỆU",
    title: "PostgreSQL Thực chiến",
    description: "Thiết kế và truy vấn dữ liệu quan hệ cho ứng dụng thực tế.",
    price: 499,
    icon: Database,
    accent: "text-sdev-pink bg-sdev-pink/10",
    glow: "bg-sdev-pink/10",
    topics: [
      "Thiết kế bảng và quan hệ",
      "SQL và chỉ mục",
      "Giao dịch và tối ưu truy vấn",
    ],
    stack: ["PostgreSQL", "SQL", "Database"],
  },
  {
    id: "docker",
    number: "09",
    category: "TRIỂN KHAI",
    title: "Docker Cho Developer",
    description: "Đóng gói ứng dụng và tạo môi trường chạy nhất quán.",
    price: 449,
    icon: Container,
    accent: "text-sdev-cyan bg-sdev-cyan/10",
    glow: "bg-sdev-cyan/10",
    topics: [
      "Image và container",
      "Dockerfile và Compose",
      "Chạy ứng dụng nhiều dịch vụ",
    ],
    stack: ["Docker", "Compose", "DevOps"],
  },
  {
    id: "redis",
    number: "10",
    category: "DỮ LIỆU",
    title: "Redis Thực chiến",
    description: "Dùng Redis để tăng tốc các luồng đọc và xử lý dữ liệu.",
    price: 399,
    icon: Database,
    accent: "text-sdev-pink bg-sdev-pink/10",
    glow: "bg-sdev-pink/10",
    topics: [
      "Kiểu dữ liệu Redis",
      "Caching và TTL",
      "Tích hợp Redis với backend",
    ],
    stack: ["Redis", "Caching", "Node.js"],
  },
  {
    id: "bullmq",
    number: "11",
    category: "BACKEND",
    title: "BullMQ & Background Jobs",
    description:
      "Đưa các tác vụ nặng ra hàng đợi để ứng dụng phản hồi tốt hơn.",
    price: 449,
    icon: Workflow,
    accent: "text-sdev-cyan bg-sdev-cyan/10",
    glow: "bg-sdev-cyan/10",
    topics: [
      "Queue, worker và job",
      "Retry và xử lý lỗi",
      "Tích hợp BullMQ với Redis",
    ],
    stack: ["BullMQ", "Redis", "Node.js"],
  },
] as const
